site_name: Prodigy API Wrapper
site_url: https://prodigy.readthedocs.io/en/latest/
repo_url: https://github.com/hostedposted/Prodigy

nav:
    - Home: index.md
    - Python:
        - Python: python/index.md
        - Tokenify: python/tokenify.md
        - Player Data:
            - Getting Player Data: python/player.md
            - Updating Player Data: python/update_player.md
        - GameData: python/gameData.md
        - GameStatus: python/gameStatus.md
    - JavaScript:
        - JavaScript: javascript/index.md
        - Tokenify: javascript/tokenify.md
        - Player Data:
            - Getting Player Data: javascript/player.md

plugins:
    - search
    - git-revision-date-localized:
        type: timeago
        enable_creation_date: true
        timezone: EST

theme:
    name: "material"
    palette:
        scheme: slate
        primary: red
        accent: red

extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
    - https://code.jquery.com/jquery-3.6.0.min.js
    - config.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/vs2015.min.css
